<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-S4TC4KCE" failures="1" tests="2" name="TestRunner.CucumberTestRunner" time="13.484" errors="0" timestamp="2025-06-14T15:18:57 IST" skipped="0">
  <testcase classname="TestRunner.CucumberTestRunner" name="runScenario" time="4.172"/>
  <testcase classname="TestRunner.CucumberTestRunner" name="runScenario" time="9.312">
    <failure message="login test passed expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: login test passed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinations.LoginStepDefinations.User_validate_the_login_page_is_working(LoginStepDefinations.java:50)
at âœ½.User validate the Login page is working(file:///C:/Users/hasan/EclipseWorkspace/Selenium_CucumberFramework/src/test/resources/Features/LoginTDD.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestRunner.CucumberTestRunner -->
